### ISSUE TITLE
Circular Cross Correlation

### ISSUE THREAD

**Issue by narahahn** [david1412/Time-varying--MIMO#2]
https://github.com/david1412/Time-varying--MIMO/blob/7485f3b0f09574e49d81562930913e82c641ec36/SISO4.py#L344-L345

This seems to be an unnecessary copy of the same function.

**Comment by david1412** [comment]
I will remove the function . I have a question , when i run the program . I am getting 4 outputs  in the code, it is because of the N=4 ?
