### ISSUE TITLE
systemdistance extension 

### ISSUE THREAD

**Issue by david1412** [david1412/Time-varying--MIMO#5]
I am trying out system distance with different angular speeds and i come up with the new update in mean time.

**Comment by david1412** [comment]
system distance with angular speeds .. once check the plot 
![sd](https://user-images.githubusercontent.com/30881405/33352431-27c09c5a-d4a9-11e7-9520-102b18018a09.png)
im trying out 1. critical 2. over and under sampling with different angular speeds.

**Comment by narahahn** [comment]
* The system distance is quite large than expected, I'm afraid there are some errors in the code.
Please check my [comments](https://github.com/david1412/Time-varying--MIMO/commit/342093e4cd8a8d1e581d17507f46fe1578f54d29).

* What is `Sigma`?

* When you plot something, please label the axes: what it is and which unit is has.

**Comment by david1412** [comment]
. I will modify it 
. Sigma* / its Omega there
![systemdistance](https://user-images.githubusercontent.com/30881405/33377453-d089cc18-d511-11e7-8c3d-1ef3fb18c4cf.png)

i labelled it with axes .. its for your reference .

**Comment by narahahn** [comment]
If you make changes, please push it to the repository so that I can test it.

**Comment by david1412** [comment]
I used the desktop version and i forgot to push at that time.. now I pushed into repository .

**Comment by david1412** [comment]
New plot:  system identification 
![new image](https://user-images.githubusercontent.com/30881405/33386757-05962176-d52c-11e7-8ffb-b4b17567e2ad.png)

**Comment by narahahn** [comment]
I guess the angular speeds are not
```
0.5, 4, 8
```
but
```
2*np.pi/0.5, 2*np.pi/4, 2*np.pi/8
```

**Comment by david1412** [comment]
I gave the angular speeds Q=[8,4,0.5]

**Comment by narahahn** [comment]
Please push all the changes to the repository, so that I can run the same code as yours.

**Comment by david1412** [comment]
I pushed all my changes to the repository . please check

**Comment by narahahn** [comment]
The parameter `Q` determines the angular speed of the microphone `Omega` which is
```
Omega = 2 * np.pi / Q
```
In your recent script, one of the `Q` value is `4.57`. I guess you considered the upper bound of the angular speed that avoid aliasing,
```
c / N / R
```
which is `4.573333...` in your experimental setup.
However, `c / N / R` should be `Omega` not the parameter `Q`.
If you want to run a simulation in which the angular speed is exactly `c / N / R`, you should find a `Q` that satisfies
```
c / N / R = 2 * np.pi / Q
```

**Comment by david1412** [comment]
yes i understood the concept , 

i took c=343 and computed with the formula . I got Q= 0.018318324510727655 
should i take the values like Q=0.19 etc ?

**Comment by david1412** [comment]
I am getting this error ,, TypeError: denominator() missing 1 required positional argument: 'psi'

in line 418 .. whats the error about ?

**Comment by narahahn** [comment]
According to its definition `denominator` requires 2 input arguments.

**Comment by narahahn** [comment]
The indentations are all messed up. How are you pushing your changes to the repository? Do you copy your script and paste it in the web browser?

Please try to use the `push` and `pull` functionality in git. This will avoid most of the problem we are having right now.

**Comment by david1412** [comment]
I am using Github desktop version . I am opening the system distance file and making changes .

opening the file>data insertion>save>commit changes with description>push .. I am using push only .. 

starting i used to copy the code in the git but from few weeks im using git desktop version .

**Comment by david1412** [comment]
i am getting one error in the code : i changed the denominator to  File "E:/Thesis/projects/new/Neuer Ordner/new11.py", line 419, in <module>
    denom = denominator(impulse_response[:,psi])
#h(phi,n) > orginal impulse response

TypeError: denominator() missing 1 required positional argument: 'psi'
only one error im getting

**Comment by narahahn** [comment]
According to its definition, `denominator()` takes 2 input arguments, but only one is used. So you can change it such that it only takes 1 input that is actually used.

https://github.com/david1412/Time-varying--MIMO/blob/809a33b60f3a8dbd36597768efb9bc6c65335e82/systemdistance.py#L13-L14

Then you have to change the following line:

https://github.com/david1412/Time-varying--MIMO/blob/809a33b60f3a8dbd36597768efb9bc6c65335e82/systemdistance.py#L122
