### ISSUE TITLE
System distances for diﬀerent angular speeds Ω ( SNR)

### ISSUE THREAD

**Issue by david1412** [david1412/Time-varying--MIMO#6]
If i want to calculate the average speed distance at Ω .. 

can i use the formula Ω=360/7/8/9 

7,8,9 are ? 

actual formula for Ω= c/ro*N

**Comment by narahahn** [comment]
I guess you mean the average "System" distance, right?

So far, you have one value (System distance) for each target angle. The average system distance is the system distance averaged over all angles.

Please notice that you are saving `20*np.log10(system_distance)` to `D`, but that is actually the system distance represented in dB scale. If you want to average the system distance, the value of `system_distance` has to be averaged, not `20*np.log10(system_distance)`.

The Formular you mentioned looks similar to the anti-aliasing condition for the angular speed, but it's not correct. It is
```
Omega = c / r0 / N
```
But I still don't understand what it has to do with the average system distance. What's 7, 8, 9?

**Comment by david1412** [comment]
in your paper i saw Ω= 360/7 , 360/8

**Comment by narahahn** [comment]
Those are the angular speeds (in degree).

I think I still don't understand your question. What are you going to do with `Omega`?

**Comment by david1412** [comment]
doubt is cleared .. I am not doing anything with Omega .. But in the average distance implementation i need omega value to draw the dotted line.
