### ISSUE TITLE
Mean System Distance

### ISSUE THREAD

**Issue by narahahn** [david1412/Time-varying--MIMO#8]
The average value of system distance is computed incorrectly. We already discussed this error before in our meeting. Please correct it in `average_fwai`

https://github.com/david1412/Time-varying--MIMO/blob/217d06d160655bff32c991344a23d17d5d1a0a0c/utility.py#L383-L389

In [Avg_System_distance_MISO.py](Avg_System_distance_MISO.py) you give `np.linspace(90, 270, num=K)` into `average_fwai`, which I don't understand.

https://github.com/david1412/Time-varying--MIMO/blob/217d06d160655bff32c991344a23d17d5d1a0a0c/Avg_System_distance_MISO.py#L105-L108

**Comment by narahahn** [comment]
When I run your code [Avg_System_distance_MIMO.py](Avg_System_distance_MIMO.py), I get the following figures.

![mic1](https://user-images.githubusercontent.com/8125968/34486760-8b1c3582-efd1-11e7-98c6-66c2ae9a8afc.png)
![mic2](https://user-images.githubusercontent.com/8125968/34486759-8b015dca-efd1-11e7-9e1b-1e6e16bdaad7.png)

They do not seem to be right, because the system distance is supposed to decrease for slower motions.

**Comment by david1412** [comment]
1.I will correct the plots .
2.In Avg_System_distance_MISO.py you give np.linspace(90, 270, num=K) into average_fwai, which I don't understand. ( i will check and revert in a moment)
3The average value of system distance is computed incorrectly. We already discussed this error before in our meeting. Please correct it in average_fwai ,# yes,we discussed in the previous meeting 

as far i understood from the meeting. i need to write code as 

np.mean(D,axis=-1)
pl.plot(np.mean(D,axis=-1))

if am wrong in understanding , please send me the procedure again. Thankyou

**Comment by david1412** [comment]
MIMO average System distance are modified ( i used mics)

in line 109,114,119,124, 20*log 10 is replaced in db . I got this plots ,please find below for mic1 and mic2 

![mic1](https://user-images.githubusercontent.com/30881405/34579734-927ef5ca-f18a-11e7-9cad-1d806acfeab5.png)
![mic2](https://user-images.githubusercontent.com/30881405/34579739-973765c0-f18a-11e7-8719-7b0238fb7580.png)


-----------------------------
MISO plot ( in line 107,112,117,122, 20*log 10 is replaced in db )

![miso](https://user-images.githubusercontent.com/30881405/34579834-f143b726-f18a-11e7-8206-4f983dac3493.png)

**Comment by david1412** [comment]
I have a question : Are the results fine in system distance MISO and MIMO .. I got this plots ..

![mic1](https://user-images.githubusercontent.com/30881405/34636785-5b422da0-f2a9-11e7-83fb-82793b81ef83.png)
![mic1 1](https://user-images.githubusercontent.com/30881405/34636798-6f0b82d2-f2a9-11e7-81f7-873a93fd12da.png)
![mic2](https://user-images.githubusercontent.com/30881405/34636799-7345b8cc-f2a9-11e7-8374-6c3e654098e3.png)
![mic2 2](https://user-images.githubusercontent.com/30881405/34636801-74dffc60-f2a9-11e7-8bda-f36b765c04dd.png)
![sys mic1](https://user-images.githubuser
![sdmic1](https://user-images.githubusercontent.com/30881405/34636810-7b5b4856-f2a9-11e7-8556-e7b247fe32d0.png)
![sd mic2](https://user-images.githubusercontent.com/30881405/34636811-7ec7cb54-f2a9-11e7-84f0-6851116496b6.png)
![sysmic2](https://user-images.githubusercontent.com/30881405/34636812-81b20122-f2a9-11e7-891e-181e039dae6e.png)


content.com/30881405/34636809-792a0a90-f2a9-11e7-95d8-39a09106f0cc.png)

**Comment by narahahn** [comment]
Great. The impulse responses seem OK.

But the system distance still looks strange.
Are you sure that the horizontal axes are the angular speed and the vertical axes are in decibels?

**Comment by david1412** [comment]
# 2 loud speakers used in the code ..( i got 8 individual interpolation IR) and (4 sysstem distance Mic1 and mic2) 
# c.f with your paper( it seems better than earlier results ) 
please find the plots below. 

![sinc2](https://user-images.githubusercontent.com/30881405/34649944-d25497ec-f3b8-11e7-83e9-d8b05aeb45df.png)

![spline2](https://user-images.githubusercontent.com/30881405/34649942-d0c0b44c-f3b8-11e7-9358-5f43a2838628.png)

![nn2](https://user-images.githubusercontent.com/30881405/34649941-ce56377c-f3b8-11e7-83d1-c34676cc36ee.png)

![irlinear 2](https://user-images.githubusercontent.com/30881405/34649940-c86c26dc-f3b8-11e7-83ab-11eee9cbcb7e.png)

![ir sinc](https://user-images.githubusercontent.com/30881405/34649937-bfb2b13c-f3b8-11e7-8ca5-1a67406a0498.png)

![ir spline](https://user-images.githubusercontent.com/30881405/34649936-bb5f94b0-f3b8-11e7-9567-b2d535a743a2.png)

![ir nn mic1](https://user-images.githubusercontent.com/30881405/34649932-b28f66a8-f3b8-11e7-8711-da67eec258af.png)

![sdmic2](https://user-images.githubusercontent.com/30881405/34649928-a210d01e-f3b8-11e7-81a4-4807167223f8.png)

![sdmic2 2](https://user-images.githubusercontent.com/30881405/34649927-9fa2c238-f3b8-11e7-90e1-801032a92a1c.png)

![sdmic1 1](https://user-images.githubusercontent.com/30881405/34649925-9cc76a46-f3b8-11e7-8d0f-57b7308b4515.png)
It looks strange ,i modified some code and i got this results. The horizontal and vertical are in angular speed and decibles respectively. 


![sd mic1](https://user-images.githubusercontent.com/30881405/34649924-9866a304-f3b8-11e7-9f31-65bf320e6ee1.png)

![ir-linear-mic1](https://user-images.githubusercontent.com/30881405/34649931-af9f2226-f3b8-11e7-8ba1-ab9e867ed222.png)

**Comment by david1412** [comment]
![avg2](https://user-images.githubusercontent.com/30881405/34655799-1b470fb4-f410-11e7-94b7-632a019efaa1.png)

![avg1](https://user-images.githubusercontent.com/30881405/34655797-1889bd26-f410-11e7-98f4-944ef9ea90fb.png)
Results of MIMO and MISO ( average system distance ) 
![average sys miso](https://user-images.githubusercontent.com/30881405/34655795-1299543a-f410-11e7-8622-238e8d645658.png)

**Comment by david1412** [comment]
# first 2 plots from MIMO 
last plot is from MISO , i think the system distance is decreased for slower motions . If the plots are good, i will update the code as per your suggestion.

**Comment by david1412** [comment]
MIMO plots seem to be strange, I modified the code and I got the plots below.

![mimo2](https://user-images.githubusercontent.com/30881405/34740580-2dcbf1ce-f580-11e7-8ae4-4cf1b2be0309.png)

![mimo](https://user-images.githubusercontent.com/30881405/34740576-2a4da9e8-f580-11e7-965f-eb41ea6a1f0f.png)

**Comment by david1412** [comment]
MIMO system distance plots , omega=2radians/sec , line 203 is modified Phi[1, :] = np.roll(Phi[0,:], int(K/2))
-----------------------------------------
![mic2 2](https://user-images.githubusercontent.com/30881405/34843751-b17b84a4-f70f-11e7-9f48-d64cfb2737e2.png)

![mic2](https://user-images.githubusercontent.com/30881405/34843749-aea98c1c-f70f-11e7-8784-c2e824a1ebec.png)

![sysmic1 1](https://user-images.githubusercontent.com/30881405/34843742-aa4cce86-f70f-11e7-8680-e42afad92eed.png)

![sysmic1](https://user-images.githubusercontent.com/30881405/34843741-a7744e28-f70f-11e7-817c-057db6c9f5d7.png)
![mic1l](https://user-images.githubusercontent.com/30881405/34843763-b7850faa-f70f-11e7-9f4d-a70751f2bd1c.png)
![mic2l](https://user-images.githubusercontent.com/30881405/34843778-c1baccd0-f70f-11e7-8090-881ca86cdc57.png)
![mic1sinc](https://user-images.githubusercontent.com/30881405/34843780-c50b8974-f70f-11e7-8c3d-3282d50faba0.png)
![mic2sinc](https://user-images.githubusercontent.com/30881405/34843788-c926889c-f70f-11e7-88bb-07bd0985fb07.png)
![mic1sp](https://user-images.githubusercontent.com/30881405/34843791-cbe9d0f2-f70f-11e7-8f1e-9511dd67c6c0.png)
![mic2sp](https://user-images.githubusercontent.com/30881405/34843793-cf010a30-f70f-11e7-9e46-fc1c2d2d881d.png)
![mic2nn](https://user-images.githubusercontent.com/30881405/34843801-d718c302-f70f-11e7-8f35-ab6e9b26d528.png)
![mic2 2nn](https://user-images.githubusercontent.com/30881405/34843806-dad4eb56-f70f-11e7-8f6b-baae94ebbf45.png)

**Comment by david1412** [comment]
![sysd2](https://user-images.githubusercontent.com/30881405/34844257-2a222024-f711-11e7-896d-584f4845561f.png)
MISO system distance ,omega=2 radians/second. I the impulse was flipped. I adjusted it

![sp2](https://user-images.githubusercontent.com/30881405/34844233-14a8b4ec-f711-11e7-84cf-44d5338fe3d1.png)

![sp1](https://user-images.githubusercontent.com/30881405/34844231-12eee5f4-f711-11e7-92bd-cb3da6a84229.png)

![sinc1](https://user-images.githubusercontent.com/30881405/34844225-111e6ab0-f711-11e7-8a3b-6e4756571631.png)

![sin2](https://user-images.githubusercontent.com/30881405/34844221-0fb1ce74-f711-11e7-80a5-3e02839603ba.png)

![nn2](https://user-images.githubusercontent.com/30881405/34844220-0c33d01c-f711-11e7-99b2-6a532beb7f12.png)

![nn1](https://user-images.githubusercontent.com/30881405/34844217-0a842faa-f711-11e7-8fb8-aa26df5a0149.png)

![l2](https://user-images.githubusercontent.com/30881405/34844215-092b1a06-f711-11e7-86f9-d820bac4676e.png)


![l1](https://user-images.githubusercontent.com/30881405/34844209-07669222-f711-11e7-82c2-e77f2fe8d5a2.png)
![sysd](https://user-images.githubusercontent.com/30881405/34844254-274d094a-f711-11e7-8a29-256125f5c6dd.png)

**Comment by david1412** [comment]
MIMO plots ( AMIMO,AMISO)

![avgmiso](https://user-images.githubusercontent.com/30881405/34896767-603d3e70-f7eb-11e7-95bd-c43829668a4b.png)

![avgmimo2](https://user-images.githubusercontent.com/30881405/34896761-5bcaa92c-f7eb-11e7-9ee9-9b6fa280904e.png)

![avgmimo1](https://user-images.githubusercontent.com/30881405/34896758-598e6400-f7eb-11e7-866c-ec7c31635e33.png)

**Comment by david1412** [comment]
![miso avgerage sd](https://user-images.githubusercontent.com/30881405/34909141-d9351414-f89b-11e7-9800-d928eab3c2a5.png)

![mimoavgsd2](https://user-images.githubusercontent.com/30881405/34909140-d4a76028-f89b-11e7-924e-09ac856c0c42.png)
MISO and MIMO avgSD results 
![mimoavgsd](https://user-images.githubusercontent.com/30881405/34909138-d06d9888-f89b-11e7-9e1c-4f19987ce6ca.png)

**Comment by david1412** [comment]
![mimoavgsd2](https://user-images.githubusercontent.com/30881405/34909155-0742f4f2-f89c-11e7-974c-0ffcbe36cbcb.png)
![miso avgerage sd](https://user-images.githubusercontent.com/30881405/34909151-fe088af0-f89b-11e7-96f6-a898ab1219eb.png)
![mimoavgsd](https://user-images.githubusercontent.com/30881405/34909153-03f78e16-f89c-11e7-9f91-011e523408ee.png)
